version: "3"
services:
  server:
    image: tumasiantum/sbt_dev_ops:serverv1
    ports:
      - 1234:1234
  client:
    image: tumasiantum/sbt_dev_ops:clientv1
    network_mode: host
    depends_on:
      - server
